// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewWallet() {
  return window['go']['main']['App']['CreateNewWallet']();
}

export function EstimateGasPrice() {
  return window['go']['main']['App']['EstimateGasPrice']();
}

export function EstimateTransactionFee(arg1, arg2, arg3) {
  return window['go']['main']['App']['EstimateTransactionFee'](arg1, arg2, arg3);
}

export function ExportKeystore(arg1, arg2) {
  return window['go']['main']['App']['ExportKeystore'](arg1, arg2);
}

export function GetETHBalance(arg1) {
  return window['go']['main']['App']['GetETHBalance'](arg1);
}

export function GetTransactionHistory(arg1) {
  return window['go']['main']['App']['GetTransactionHistory'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SendTransaction(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendTransaction'](arg1, arg2, arg3);
}

export function ValidateAddress(arg1) {
  return window['go']['main']['App']['ValidateAddress'](arg1);
}

export function ValidateKeystorePassword(arg1, arg2) {
  return window['go']['main']['App']['ValidateKeystorePassword'](arg1, arg2);
}
