// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wallet} from '../models';
import {ethclient} from '../models';

export function CreateNewWallet():Promise<wallet.WalletAccount>;

export function EstimateGasPrice():Promise<string>;

export function EstimateTransactionFee(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportKeystore(arg1:string,arg2:string):Promise<string>;

export function GetETHBalance(arg1:string):Promise<string>;

export function GetTransactionHistory(arg1:string):Promise<Array<ethclient.Transaction>>;

export function Greet(arg1:string):Promise<string>;

export function SendTransaction(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ValidateAddress(arg1:string):Promise<boolean>;

export function ValidateKeystorePassword(arg1:string,arg2:string):Promise<boolean>;
